### ISSUE TITLE
how is it different from chokidar?

### ISSUE THREAD

**Issue by iamstarkov** [andreyvit/fsmonitor.js#10]
chokidar is crossplatform and proved to behave well, by gulp and webpack usage. So what are pros & cons of using fsmonitor versa chokidar?

**Comment by andreyvit** [comment]
@iamstarkov Well for one thing, this one is pretty much unmaintained. :-) I'd say, stay away — I no longer have a use for this one, and nobody has stepped up to maintain it.

But another difference is that if you, say, delete a folder, this project reports every file in that folder as deleted, while other projects would only report the folder deletion.
